services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nutricion
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run start:dev

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Front:/app
    working_dir: /app
    command: npm run dev
